### ISSUE TITLE
获取作业任务类型ScriptJob~

### ISSUE THREAD

**Issue by jieblog** [xjzrc/elastic-job-lite-spring-boot-starter#1]
![image](https://user-images.githubusercontent.com/12409311/37392387-f71dcb56-27a8-11e8-8de3-fa59dbaebd86.png)

你好，我注意到job 扫描的时候有这个问题~

**Comment by xjzrc** [comment]
谢谢反馈，一直没用过脚本作业配置。这一块也就没完善。新版本1.0.1已经支持脚本任务。

**Comment by jieblog** [comment]
nice~
